name: env-extract-code
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - ld_impl_linux-64=2.44
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libsqlite=3.50.4
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - numpy=1.26.4
  - openssl=3.5.4
  - pip=25.2
  - python=3.11.14
  - python_abi=3.11
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - wheel=0.45.1
  - pip:
      - accelerate==1.11.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - filelock==3.20.0
      - fsspec==2025.9.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.2
      - kneed==0.8.5
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - psutil==7.1.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.10.23
      - requests==2.32.5
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - sentence-transformers==5.1.1
      - six==1.17.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.2.2
      - torchvision==0.17.2
      - tqdm==4.67.1
      - transformers==4.57.1
      - triton==2.2.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
prefix: /home/hice1/zgoel3/scratch/conda_envs/env-extract-code
